export const bestuursorgaanSuggestions = [
  "Belastingdienst",
  "Uitvoeringsinstituut Werknemersverzekeringen (UWV)",
  "Centraal Justitieel Incassobureau (CJIB)",
  "Dienst Uitvoering Onderwijs (DUO)",
  "Sociale Verzekeringsbank (SVB)",
  "Rijksdienst voor Ondernemend Nederland (RVO)",
  "Immigratie- en Naturalisatiedienst (IND)",
  "Centraal Administratie Kantoor (CAK)",
  "Rijksdienst voor Identiteitsgegevens (RvIG)",
  "Rijkswaterstaat",
  "Nederlandse Voedsel- en Warenautoriteit (NVWA)",
  "Inspectie Gezondheidszorg en Jeugd (IGJ)",
  "Autoriteit Persoonsgegevens",
  "Autoriteit Consument en Markt (ACM)",
  "De Nederlandsche Bank (DNB)",
  "Autoriteit Financiele Markten (AFM)",
  "Ministerie van Algemene Zaken",
  "Ministerie van Binnenlandse Zaken en Koninkrijksrelaties",
  "Ministerie van Buitenlandse Zaken",
  "Ministerie van Defensie",
  "Ministerie van Economische Zaken",
  "Ministerie van Financien",
  "Ministerie van Infrastructuur en Waterstaat",
  "Ministerie van Justitie en Veiligheid",
  "Ministerie van Landbouw, Visserij, Voedselzekerheid en Natuur",
  "Ministerie van Onderwijs, Cultuur en Wetenschap",
  "Ministerie van Sociale Zaken en Werkgelegenheid",
  "Ministerie van Volksgezondheid, Welzijn en Sport",
  "Ministerie van Volkshuisvesting en Ruimtelijke Ordening",
  "Gemeente Amsterdam",
  "Gemeente Rotterdam",
  "Gemeente Den Haag",
  "Gemeente Utrecht",
  "Gemeente Eindhoven",
  "Gemeente Tilburg",
  "Gemeente Groningen",
  "Gemeente Almere",
  "Gemeente Breda",
  "Gemeente Nijmegen",
  "Gemeente Enschede",
  "Gemeente Haarlem",
  "Gemeente Arnhem",
  "Gemeente Zaanstad",
  "Gemeente Amersfoort",
  "Gemeente Apeldoorn",
  "Gemeente Zwolle",
  "Provincie Drenthe",
  "Provincie Flevoland",
  "Provincie Friesland",
  "Provincie Gelderland",
  "Provincie Groningen",
  "Provincie Limburg",
  "Provincie Noord-Brabant",
  "Provincie Noord-Holland",
  "Provincie Overijssel",
  "Provincie Utrecht",
  "Provincie Zeeland",
  "Provincie Zuid-Holland",
  "Waterschap Amstel, Gooi en Vecht",
  "Waterschap Brabantse Delta",
  "Waterschap De Dommel",
  "Waterschap Drents Overijsselse Delta",
  "Waterschap Hollandse Delta",
  "Waterschap Limburg",
  "Waterschap Noorderzijlvest",
  "Waterschap Rijn en IJssel",
  "Waterschap Rivierenland",
  "Waterschap Scheldestromen",
  "Waterschap Vallei en Veluwe",
  "Waterschap Vechtstromen",
  "Waterschap Zuiderzeeland"
] as const;

export function filterBestuursorganen(input: string, maxResults = 12): string[] {
  const query = input.trim().toLowerCase();
  if (!query) {
    return bestuursorgaanSuggestions.slice(0, maxResults);
  }

  return bestuursorgaanSuggestions
    .filter((entry) => entry.toLowerCase().includes(query))
    .slice(0, maxResults);
}
